### ISSUE TITLE
ImportError: No module named align

### ISSUE THREAD

**Issue by KoteshwarSurga** [arunmandal53/facematch#8]
Hi,
I am trying to execute your code for detection but it is throwing error as

ImportError: No module named align

**Comment by arunmandal53** [comment]
use python3 and run from the script directory

**Comment by KoteshwarSurga** [comment]
TypeError: reduce_max() got an unexpected keyword argument 'keepdims'

Thank u for your response when i tried with python3 it is throwing the
above error.

**Comment by arunmandal53** [comment]
seems like Tensorflow version issue see https://github.com/arunmandal53/facematch/commit/d019ae353b7bbbb0651c1ad7143918b07a5fe4ec#diff-7b86cf4cb688073525084093b33a8889

**Comment by KoteshwarSurga** [comment]
Thank u I installed  your requirements.txt and now it is working.

**Comment by KoteshwarSurga** [comment]
Hi,

I have an image of me in that me and my friends are wearing college Id
cards.

When I used the face detect demo code it is detecting faces in the id card
and also the person but the problem is when I used to crop the images it
was croping the small images of IDs cards not the person images not all the
images some images

I searched a lot but I didn't find the solution
Cab you help me in this problem.

**Comment by arunmandal53** [comment]
Does it show rectangle properly on faces ? If yes then use that rect coordinates to crop.

**Comment by KoteshwarSurga** [comment]
It showing rectangle accurately but it was drawing my face and also my
identity card face which iam wearing.
When I used to crop it is cropping my id card photo and not my face and
when I am comparing with my face it was showing false results.

**Comment by KoteshwarSurga** [comment]
Hi,
when i used your face_match_demo.py i got this error.
Traceback (most recent call last):
  File "face_match_demo.py", line 76, in <module>
    distance = compare2face(img1, img2)
  File "face_match_demo.py", line 62, in compare2face
    face1 = getFace(img1)
  File "face_match_demo.py", line 40, in getFace
    bounding_boxes, _ = detect_face.detect_face(img, minsize, pnet, rnet, onet, threshold, factor)
  File "/home/tgt/Pictures/facematch-master/align/detect_face.py", line 332, in detect_face
    boxes, _ = generateBoundingBox(out1[0,:,:,1].copy(), out0[0,:,:,:].copy(), scale, threshold[0])
TypeError: 'float' object is not subscriptable

**Comment by Legionof7** [comment]
When running with Python3, I get the error `Traceback (most recent call last):
  File "face_embeddings_demo.py", line 1, in <module>
    import tensorflow as tf
ModuleNotFoundError: No module named 'tensorflow'`
